name: Android Build

on:
  push:
    branches: [ main ]
env:
  CACHE_BUNDLER: ~/.bundler

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Cache gradle
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-


      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'


      - name: Install Dependencies
        run: gem install bundler && bundle install


      - name: Create local.properties File
        run: cat /home/runner/work/CatApp/CatApp/local.properties | base64

      - name: Saving credentials in local.properties file
        env:
          DATA: ${{ secrets.PROPERTIES_CONTENT }}
        run: echo $DATA > /home/runner/work/CatApp/CatApp/local.properties

      - name: Create service_account.json File
        run: cat /home/runner/work/CatApp/CatApp/service_account.json | base64

      - name: Saving credentials in service_account.json file
        env:
          DATA: ${{ secrets.FIREBASE_APP_DISTRIBUTION_SERVICE_ACCOUNT }}
        run: echo $DATA > /home/runner/work/CatApp/CatApp/service_account.json

      - name: Run Fastlane Beta
        uses: maierj/fastlane-action@v3.0.0
        with:
          lane: beta
          subdirectory: fastlane





